name: build library

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Cloning repo
      -
        name: Checkout repo
        id: checkout-repo
        uses: actions/checkout@v2
        with:
          repository: sdkwa/whatsapp-api-client
          path: whatsapp-api-client
          fetch-depth: 100
      # Installing nodejs
      -
        name: Use Node.js 12.21.0
        uses: actions/setup-node@v2
        with:
          node-version: "12.21.0"
      # Installing dependencies
      - 
        name: Install dependencies
        run: |
            cd whatsapp-api-client
            npm install
            npm install -g rollup
      # Building nodejs and browser libraries
      - 
        name: Building the libraries
        run: |
          cd whatsapp-api-client
          npm run build