name: build library

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Cloning repo
      -
        name: Checkout repo
        id: checkout-repo
        uses: actions/checkout@v2
        with:
          repository: sdkwa/whatsapp-api-client-js
          path: whatsapp-api-client-js
          fetch-depth: 100
      # Installing nodejs
      -
        name: Use Node.js 20.18.1
        uses: actions/setup-node@v2
        with:
          node-version: "20.18.1"
      # Installing dependencies
      - 
        name: Install dependencies
        run: |
            cd whatsapp-api-client-js
            npm install
            npm install -g rollup
      # Building nodejs and browser libraries
      - 
        name: Building the libraries
        run: |
          cd whatsapp-api-client-js
          npm run build
